### ISSUE TITLE
Add linearIntercept

### ISSUE THREAD

**Issue by ayham-1** [realaltffour/GraphSolver#20]
# Feature
This should not be hard, just add a class following the style of the linear class, but for calculating the intercept of two lines.

# If you want help:
Mention @realaltffour or @AliAlboainin96 or send a tweet, [twitter](https://twitter.com/altf_four)

**Comment by xypnox** [comment]
Hi I would like to work on this. 

For clarification, the linear intercept of the two lines would be the point at which they intersect right?

**Comment by ayham-1** [comment]
Hey @xypnox Go for it🚀!
And yes you are right the linear intercept of two lines would be the point at which they intersect.
