### ISSUE TITLE
OOP calcLinearIntercept.py

### ISSUE THREAD

**Issue by ayham-1** [realaltffour/GraphSolver#23]
Make calcLinearIntersection() in a class, following calcLinear class structure.

Mention @realaltffour for help!

**Comment by TriptSharma** [comment]
Working on it :)

**Comment by TriptSharma** [comment]
@realaltffour The function is the same as method calcLineaIntersection() of class Linear in calcLinear.py. So, what exactly needs to be done? Can you please explain.

**Comment by ayham-1** [comment]
Hey @TriptSharma, Go for it 🚀!, yes it is the same, just put it in a class just like calcLinear().
Fixing the calcLineaIntercept to calcLinearIntercept would also be nice!

**Comment by ayham-1** [comment]
This has been done at: #26
