### ISSUE TITLE
Apply PEP8 on all files.

### ISSUE THREAD

**Issue by ayham-1** [realaltffour/GraphSolver#24]
This won't be hard.

**Comment by adamllwilliams** [comment]
Is it OK if I take this? Thanks

**Comment by ayham-1** [comment]
Hey @README1ST, Go for it 🚀!

**Comment by maltzsama** [comment]
Can I help?

**Comment by adamllwilliams** [comment]
> Can I help?

I'm about to open a PR, I'll reference the issue. There might be a couple of changes regarding max line length that you could give your opinion on/make changes.
